FROM ubuntu:22.04

WORKDIR /home/local

# Setting up the default locale to en_US.UTF-8
# RUN localedef --no-archive -i en_US -f UTF-8 en_US.UTF-8 && \
#    export LANG=en_US.UTF-8

# Time Zone 
RUN ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone 

# apt update 
RUN apt update 

# snap 
RUN apt install -y \ 
    snapd 
# net-tools e.g. ifconfig 
RUN apt install -y \ 
    net-tools 
# python3 
RUN apt install -y \ 
    python3 \ 
    python3-pip
# gedit
RUN apt install -y \ 
    gedit

# enable GUI 
RUN apt install -y \ 
    glibc-source \ 
    dbus-x11 \ 
    packagekit-gtk3-module \ 
    libcanberra-gtk-module 

# Qt
RUN pip install \
    pyqt5-tools

# ROS2 Humble 
RUN apt install -y \ 
    software-properties-common
RUN add-apt-repository universe 
RUN apt install -y \ 
    curl 
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
RUN apt update 
RUN apt upgrade -y 
RUN apt install -y \ 
    ros-humble-desktop \
    ros-dev-tools 

## Expose 
EXPOSE 11311
## Domain iD
ENV ROS_DOMAIN_ID=0
## Setup the environment for ROS (for all users)
RUN echo "source /opt/ros/humble/setup.bash" >> /etc/bash.bashrc

# setuptools
RUN pip install setuptools==58.2.0

# User 
## Set the UID for the regular user
ARG USER_ID=1000
## Add the local user and set its UID to the specified USER_ID
RUN useradd -u $USER_ID -m local
## Add the local user to the sudoers file and allow executing sudo commands without password
RUN echo 'local ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
## Switch to the local user
USER local

# RUN rm -rf /var/lib/apt/lists/*
